Call the platform repo directly using curl

diff --git a/.github/workflows/trigger-umbrella.yml b/.github/workflows/trigger-umbrella.yml
--- a/.github/workflows/trigger-umbrella.yml
+++ b/.github/workflows/trigger-umbrella.yml
@@ -3,16 +3,50 @@ name: Update the common Platform.sh Repository
 on:
   push:
     branches:
-      - 'release/**'
-      - 'main'
+      - "release/**"
+      - "main"
 
 jobs:
   update-platform-repo:
     runs-on: ubuntu-latest
     steps:
       - name: Update the Platform Repo Submodule for Backend
-        uses: peter-evans/repository-dispatch@v2
-        with:
-          repository: os2ulf/os2udoglaer
-          event-type: update-submodule
-          client-payload: '{"submodule": "backend", "branch": "${{ github.ref_name }}", "commit": "${{ github.sha }}"}'
+        run: |
+          repo_owner="os2ulf"
+          repo_name="os2udoglaer"
+          event_type="update-submodules"
+
+          # Get the latest commit hash
+          commit_hash=${{ github.sha }}
+
+          # Get the branch name
+          branch_name=${{ github.ref_name }}
+
+          # If the branch isn't main, it's develop!
+          if [ "$branch_name" != "main" ]; then
+            branch_name="develop"
+          fi
+
+          # Valid branches are main and develop, fail on anything else
+          if [ "$branch_name" != "main" ] && [ "$branch_name" != "develop" ]; then
+            echo "Invalid branch name: $branch_name"
+            exit 1
+          fi
+
+          # Echo out the above variables
+          echo "Commit Hash: $commit_hash"
+          echo "Branch Name: $branch_name"
+          echo "Repository Owner: $repo_owner"
+          echo "Repository Name: $repo_name"
+          echo "Event Type: $event_type"
+
+          # Create a client payload
+
+          # Trigger the repository dispatch event
+          curl -L \
+            -X POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.REPO_DISPATCH_TOKEN }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
+            -d "{\"event_type\": \"$event_type\", \"client_payload\": {\"submodule\": \"backend\", \"branch\": \"$branch_name\", \"commit\": \"$commit_hash\"}}"
